# Generated by Django 2.0 on 2019-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_auto_20190305_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_between', models.CharField(blank=True, max_length=100, null=True)),
                ('first_poll', models.ImageField(blank=True, upload_to='New/%Y/%m/%d')),
                ('second_poll', models.ImageField(blank=True, upload_to='New/%Y/%m/%d')),
                ('first_poll_count', models.IntegerField(default=0)),
                ('second_poll_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Poll',
            },
        ),
    ]
