# Generated by Django 2.0 on 2019-03-11 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollapp', '0003_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='first_user_vote',
            field=models.ManyToManyField(blank=True, related_name='poll1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='second_user_vote',
            field=models.ManyToManyField(blank=True, related_name='poll2', to=settings.AUTH_USER_MODEL),
        ),
    ]
