# Generated by Django 2.0 on 2019-03-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0005_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='first_user_vote',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='second_user_vote',
        ),
    ]
