# Generated by Django 2.0.2 on 2018-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
