# Generated by Django 2.0 on 2019-03-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0006_auto_20190311_0638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscriber'},
        ),
    ]
