# Generated by Django 2.0 on 2019-03-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0007_auto_20190311_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('links', models.URLField()),
            ],
            options={
                'verbose_name': 'News Letter',
                'verbose_name_plural': 'News Letter',
            },
        ),
    ]
