# Generated by Django 2.0 on 2019-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0008_sendnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendnewsletter',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='News Title'),
        ),
    ]
