# Generated by Django 2.0 on 2019-03-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0009_auto_20190311_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
