# Generated by Django 2.0 on 2019-03-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0010_delete_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Party',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State',
            },
        ),
        migrations.AddField(
            model_name='electionupdate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollapp.State'),
        ),
    ]
