# Generated by Django 2.0 on 2019-03-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0011_auto_20190325_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionupdate',
            name='party',
            field=models.ManyToManyField(blank=True, to='pollapp.Party'),
        ),
    ]
