# Generated by Django 2.0 on 2019-03-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0012_electionupdate_party'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionupdate',
            options={'verbose_name': 'Election Update', 'verbose_name_plural': 'Election Update'},
        ),
    ]
