# Generated by Django 2.0.13 on 2019-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0015_auto_20190325_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(blank=True, max_length=100)),
                ('minisrty', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ministry',
                'verbose_name': 'Ministry',
            },
        ),
    ]
