# Generated by Django 2.0.13 on 2019-04-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0016_ministry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministry',
            old_name='minisrty',
            new_name='ministry',
        ),
    ]
